### PR TITLE
Make JS bundle 25% smaller

### PR DESCRIPTION
**Pull request by cxcorp**
The frontend JS bundle contains about 2.5MB of parsed JS, and is ~710-720kB gzipped.

Some low hanging fruits:
- remove `dotenv` from frontend as it pulls in lots of `fs`, `stream`, `process` etc node.js polyfills that aren't needed
  - I did not find any references to `process.env` that are not already handled by Create React App's env handling (`REACT_APP_`, `PUBLIC_URL`, `NODE_ENV`) so it is probably something historical
- remove all `import _ from 'lodash'` imports from the frontend and replace them with e.g. `import { groupBy } from 'lodash-es'`
   - this allows webpack's tree shaking to drop off the parts it doesn't need
   - warning: any single `import _ from 'lodash-es'` can bring back the entire lodash-es package into the bundle
   - lodash-es is marked as [`sideEffects: false`](https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects) so webpack can drop more stuff
- duplication of the `CONFIG` object in frontend because the `webpack.DefinePlugin` just basically replaces places where it is used with the entire config object (tens of times in common.js)
- apply code splitting to the main router so that each page component can be in their own bundle so user only downloads the JS for the pages they access

Starting point: JS parsed size ~2.5MB

```
File sizes after gzip:

  714.85 kB  build/static/js/main.ebca225a.js

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb
```

After removing unnecessary deps and switching to lodash-es: JS parsed size ~1.9MB

```
File sizes after gzip:

  609.78 kB (-105.07 kB)  build/static/js/main.fea1ae25.js

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb
```

After code splitting:

```
File sizes after gzip:

  406.88 kB  build/static/js/main.75ce830f.js
  41.76 kB   build/static/js/45.b365872b.chunk.js
  31.37 kB   build/static/js/67.dcdbdbed.chunk.js
  31.22 kB   build/static/js/159.538c75b5.chunk.js
  21.19 kB   build/static/js/589.6434bb6c.chunk.js
  17.89 kB   build/static/js/218.03ae125b.chunk.js
  14.51 kB   build/static/js/991.a6a7e598.chunk.js
  13.32 kB   build/static/js/150.fe881100.chunk.js
  10.23 kB   build/static/js/808.caf25c5d.chunk.js
  9.41 kB    build/static/js/551.a12e3979.chunk.js
  8.65 kB    build/static/js/206.04ff72a8.chunk.js
  6.87 kB    build/static/js/347.03715f3a.chunk.js
  5.69 kB    build/static/js/270.6e7f6e0c.chunk.js
  5.6 kB     build/static/js/27.41a31e68.chunk.js
  4.43 kB    build/static/js/463.108723d1.chunk.js
  4.23 kB    build/static/js/970.1b13141c.chunk.js
  4.21 kB    build/static/js/855.eb76830f.chunk.js
  3.64 kB    build/static/js/18.1f4b726a.chunk.js
  2.98 kB    build/static/js/884.389d3242.chunk.js
  2.56 kB    build/static/js/571.70e44aad.chunk.js
  1.21 kB    build/static/js/384.d5e7586e.chunk.js
  609 B      build/static/js/719.88ae9a90.chunk.js
```

It's still a bit hefty but noticeably smaller.

### CODE REVIEW

**Comment by Veikkosuhonen** [comment]
`lodash-es` does not work in backend:
```
palaute_dev        | /usr/src/app/src/server/services/organisationAccess/organisationAccess.js:2
palaute_dev        | [0] const _ = require('lodash-es')
palaute_dev        | [0]           ^
palaute_dev        | [0] 
palaute_dev        | [0] Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/node_modules/lodash-es/lodash.js from /usr/src/app/src/server/services/organisationAccess/organisationAccess.js not supported.
palaute_dev        | [0] Instead change the require of lodash.js in /usr/src/app/src/server/services/organisationAccess/organisationAccess.js to a dynamic import() which is available in all CommonJS modules.
palaute_dev        | [0]     at Object.<anonymous> (/usr/src/app/src/server/services/organisationAccess/organisationAccess.js:2:11)
palaute_dev        | [0]     at Object.<anonymous> (/usr/src/app/src/server/services/organisationAccess/index.js:1:89)
palaute_dev        | [0]     at Object.<anonymous> (/usr/src/app/src/server/models/modelExtensions.js:17:63)
palaute_dev        | [0]     at Object.<anonymous> (/usr/src/app/src/server/index.js:3:1) {
palaute_dev        | [0]   code: 'ERR_REQUIRE_ESM'
palaute_dev        | [0] }
```

Restoring the backend lodash imports to `lodash` fixed it

**Comment by Veikkosuhonen** [comment]
@cxcorp can you check that its ok that I changed the backend lodash imports back? I also added back lodash as a dependency, it shouldnt affect the bundle right?

**Comment by cxcorp** [comment]
The bundle size can be checked with webpack-bundle-analyzer: `npm i -D webpack-bundle-analyzer` add the required line to the `config-overrides.js` plugins array: https://www.npmjs.com/package/webpack-bundle-analyzer. The package for backend imports is probably alright, but you'll see when you build it. Theoretically there could be some sub-dependency that is okay with either lodash-es or lodash and would end up picking the worse option if both are installed.

One more size recommendation, though not related to the frontend, is having a different package.json for the frontend and backend though since Create-React-App comes with a huuuuge dependency amount which are all currently copied in the Docker image for the backend.

**Comment by Veikkosuhonen** [comment]
Checked the deps, looks fine after my commit (no lodash). 
image
The chart.js and XLSX are pretty ugly, XLSX is at least nearly unused and might get removed in the future.

> One more size recommendation, though not related to the frontend, is having a different package.json for the frontend and backend though since Create-React-App comes with a huuuuge dependency amount which are all currently copied in the Docker image for the backend.
This is apparently in the works by the TAU team who is also adding partial TS support

**Pull request merged**
